data:
  target: dataset.data_module.BIRDataModule
  params:
    # Path to training set configuration file.
    train_config: configs/dataset/rs_dlg_train.yaml
    # Path to validation set configuration file.
    val_config: configs/dataset/rs_dlg_val.yaml

model:
  # You can set learning rate in the following configuration file.
  config: configs/model/cldm_stage2.yaml
  # Path to the checkpoints or weights you want to resume. At the begining, 
  # this should be set to the initial weights created by scripts/make_stage2_init_weight.py.


  resume: pretrained/init_stage2.ckpt





lightning:
  seed: 231
  
  trainer:
    accelerator: gpu
    precision: 32
    # Indices of GPUs used for training.
    devices: 1
    strategy: ddp_find_unused_parameters_true # ddp
    # Path to save logs and checkpoints.
    default_root_dir: save_dir_stage2
    # Max number of training steps (batches).
    max_steps: 10 # 500001
    # Validation frequency in terms of training steps.
    val_check_interval: 5 # 900
    log_every_n_steps: 5 # 50
    # Accumulate gradients from multiple batches so as to increase batch size.
    accumulate_grad_batches: 1
  
  callbacks:
    # - target: model.callbacks.ImageLogger
    #   params:
    #     # Log frequency of image logger.
    #     log_every_n_steps: 1000
    #     max_images_each_step: 4
    #     log_images_kwargs: ~

    - target: model.callbacks.ModelCheckpoint
      params:

        # 第二阶段
        every_n_train_steps: 5 # 1000
        monitor: 'lpips'
        save_top_k: 1
        mode: 'min'
        filename: "{step}-{lpips:.4f}"
